# Change these first
owner: vavab # Your GitHub organization or username, where this repository lives
repo: API-monitoring # The name of this repository

sites:
  - name: API Vélib' disponibles 
    url: https://opendata.paris.fr/api/v2/catalog/datasets/velib-disponibilite-en-temps-reel/records?limit=10&offset=0&timezone=UTC
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/V%C3%A9lib-M%C3%A9tropole-Logo.png/800px-V%C3%A9lib-M%C3%A9tropole-Logo.png?20190704093440
  - name: API Chantiers en cours
    url: https://opendata.paris.fr/api/v2/catalog/datasets/chantiers-a-paris/records?limit=10&offset=0&timezone=UTC
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Logo_travaux_orange.svg/1024px-Logo_travaux_orange.svg.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /API-monitoring
  logoUrl: https://cdn-icons.flaticon.com/png/512/2930/premium/2930685.png?token=exp=1656590553~hmac=54384c860dd41864b25e886eaa55eada
  name: API Monitoring
  introTitle: "*API Monitor* allows you to watch your favorite APIs health status"
  introMessage: This is a monitoring page for APIs
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  graphs: "* * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "* * * * *"
  updateTemplate: "0 0 * * *"
  updates: "* * * * *"
  uptime: "* * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
